USE ROLE ACCOUNTADMIN;

CREATE OR REPLACE WAREHOUSE AMAZON_SENTIMENT_WH
    WAREHOUSE_SIZE='XSMALL'
    AUTO_SUSPEND= 60
    AUTO_RESUME =TRUE
    INITIALLY_SUSPENDED= TRUE;


CREATE OR REPLACE DATABASE AMAZON_SENTIMENT_DB;
CREATE OR REPLACE SCHEMA AMAZON_SENTIMENT_DB.ANALYTICS;

GRANT DATABASE ROLE SNOWFLAKE.CORTEX_USER TO ROLE ACCOUNTADMIN;

USE WAREHOUSE AMAZON_SENTIMENT_WH;
USE DATABASE AMAZON_SENTIMENT_DB;
USE SCHEMA AMAZON_SENTIMENT_DB.ANALYTICS;