USE DATABASE AMAZON_BEST_SELLERS_RATINGS_AND_REVIEWS;

DESC TABLE PUBLIC.PRODUCTS;
DESC TABLE PUBLIC.REVIEWS;

SELECT COUNT(*) AS PRODUCT_COUNT
FROM PUBLIC.PRODUCTS;

SELECT COUNT(*) AS REVIEW_COUNT
FROM PUBLIC.REVIEWS;

SELECT * FROM PUBLIC.PRODUCTS LIMIT 10;

SELECT * FROM PUBLIC.REVIEWS LIMIT 10;


--VALIDATE USABLE REVIEWS

SELECT 
COUNT(*) AS TOTAL_REVIEWS,
COUNT_IF(BODY IS NULL) AS NULL_REVIEW_TEXT,
COUNT_IF(LENGTH(TRIM(BODY)) <10) AS VERY_SHORT_REVIEWS,
COUNT_IF(STARS IS NULL) AS NULL_STAR_RATINGS,
COUNT_IF(ASIN IS NULL) AS NULL_ASIN
FROM PUBLIC.REVIEWS;

--CHECK STAR DISTRIBUTION

SELECT
STARS,
COUNT(*) AS REVIEW_COUNT
FROM PUBLIC.REVIEWS
GROUP BY STARS
ORDER BY STARS;

--CHECK VERIFIED PURCHASE VALUE


SELECT 
VERIFIED_PURCHASE,
COUNT(*) AS REVIEW_COUNT
FROM PUBLIC.REVIEWS
GROUP BY VERIFIED_PURCHASE
ORDER BY REVIEW_COUNT DESC;
