-- ============================================================
-- 03_create_review_sample.sql
-- Creates a balanced local sample to control Cortex cost.
-- Maximum: 500 reviews and 20 reviews per product.
-- ============================================================

USE WAREHOUSE AMAZON_SENTIMENT_WH;
USE DATABASE AMAZON_SENTIMENT_DB;
USE SCHEMA ANALYTICS;

CREATE OR REPLACE TABLE REVIEW_SAMPLE AS
WITH VALID_REVIEWS AS (
    SELECT
        R.ID::VARCHAR AS REVIEW_ID,
        R.ASIN::VARCHAR AS ASIN,
        R.URL::VARCHAR AS REVIEW_URL,
        R.TITLE::VARCHAR AS REVIEW_TITLE,
        TRIM(R.BODY::VARCHAR) AS REVIEW_TEXT,
        COALESCE(
            TRY_TO_DATE(R.DATE::VARCHAR, 'DY MON DD YYYY'),
            TRY_TO_DATE(R.DATE::VARCHAR)
        ) AS REVIEW_DATE,
        R.STARS::NUMBER AS STARS,
        R.USER_ID::VARCHAR AS USER_ID,
        R.VARIATION::VARCHAR AS VARIATION,
        COALESCE(R.FOUND_HELPFUL, 0)::NUMBER AS FOUND_HELPFUL,
        R.VERIFIED_PURCHASE::VARCHAR AS VERIFIED_PURCHASE,

        P.TITLE::VARCHAR AS PRODUCT_TITLE,
        P.URL::VARCHAR AS PRODUCT_URL,
        P.MAIN_IMAGE::VARCHAR AS MAIN_IMAGE,
        P.BREADCRUMBS::VARCHAR AS BREADCRUMBS,
        P.RATING::FLOAT AS PRODUCT_RATING,
        P.NUMBER_OF_RATINGS::NUMBER AS NUMBER_OF_RATINGS,

        ROW_NUMBER() OVER (
            PARTITION BY R.ASIN
            ORDER BY HASH(R.ID)
        ) AS PRODUCT_REVIEW_NUMBER

    FROM AMAZON_BEST_SELLERS_RATINGS_AND_REVIEWS.PUBLIC.REVIEWS R

    INNER JOIN
        AMAZON_BEST_SELLERS_RATINGS_AND_REVIEWS.PUBLIC.PRODUCTS P
        ON R.ASIN = P.ASIN

    WHERE R.BODY IS NOT NULL
      AND LENGTH(TRIM(R.BODY::VARCHAR)) BETWEEN 20 AND 2000
      AND R.STARS BETWEEN 1 AND 5
)
SELECT
    REVIEW_ID,
    ASIN,
    REVIEW_URL,
    REVIEW_TITLE,
    REVIEW_TEXT,
    REVIEW_DATE,
    STARS,
    USER_ID,
    VARIATION,
    FOUND_HELPFUL,
    VERIFIED_PURCHASE,
    PRODUCT_TITLE,
    PRODUCT_URL,
    MAIN_IMAGE,
    BREADCRUMBS,
    PRODUCT_RATING,
    NUMBER_OF_RATINGS,
    CURRENT_TIMESTAMP() AS LOADED_AT
FROM VALID_REVIEWS
WHERE PRODUCT_REVIEW_NUMBER <= 20
QUALIFY ROW_NUMBER() OVER (ORDER BY HASH(REVIEW_ID)) <= 500;

-- Validate the sample.
SELECT
    COUNT(*) AS TOTAL_REVIEWS,
    COUNT(DISTINCT ASIN) AS TOTAL_PRODUCTS,
    MIN(REVIEW_DATE) AS EARLIEST_REVIEW,
    MAX(REVIEW_DATE) AS LATEST_REVIEW,
    ROUND(AVG(STARS), 2) AS AVERAGE_STARS
FROM REVIEW_SAMPLE;

SELECT
    STARS,
    COUNT(*) AS REVIEW_COUNT
FROM REVIEW_SAMPLE
GROUP BY STARS
ORDER BY STARS;
