-- ============================================================
-- 08_create_views.sql
-- Creates four simple views used by Streamlit.
-- ============================================================

USE WAREHOUSE AMAZON_SENTIMENT_WH;
USE DATABASE AMAZON_SENTIMENT_DB;
USE SCHEMA ANALYTICS;

-- 1. Overall sentiment.
CREATE OR REPLACE VIEW VW_SENTIMENT_OVERVIEW AS
SELECT
    OVERALL_SENTIMENT,
    COUNT(*) AS REVIEW_COUNT,
    ROUND(
        COUNT(*) * 100.0
        / NULLIF(SUM(COUNT(*)) OVER (), 0),
        2
    ) AS REVIEW_PERCENTAGE
FROM REVIEW_SENTIMENT_ANALYSIS
GROUP BY OVERALL_SENTIMENT;


-- 2. Product-level sentiment.
CREATE OR REPLACE VIEW VW_PRODUCT_SENTIMENT AS
SELECT
    ASIN,
    PRODUCT_TITLE,
    MAX(MAIN_IMAGE) AS MAIN_IMAGE,
    MAX(PRODUCT_URL) AS PRODUCT_URL,
    MAX(PRODUCT_RATING) AS PRODUCT_RATING,
    MAX(NUMBER_OF_RATINGS) AS NUMBER_OF_RATINGS,

    COUNT(*) AS ANALYZED_REVIEWS,

    COUNT_IF(OVERALL_SENTIMENT = 'positive')
        AS POSITIVE_REVIEWS,

    COUNT_IF(OVERALL_SENTIMENT = 'negative')
        AS NEGATIVE_REVIEWS,

    ROUND(
        COUNT_IF(OVERALL_SENTIMENT = 'positive')
        * 100.0 / NULLIF(COUNT(*), 0),
        2
    ) AS POSITIVE_PERCENTAGE,

    ROUND(
        COUNT_IF(OVERALL_SENTIMENT = 'negative')
        * 100.0 / NULLIF(COUNT(*), 0),
        2
    ) AS NEGATIVE_PERCENTAGE,

    COUNT_IF(REQUIRES_ATTENTION)
        AS ATTENTION_REVIEWS,

    COUNT_IF(RATING_SENTIMENT_MATCH = FALSE)
        AS RATING_MISMATCHES

FROM REVIEW_SENTIMENT_ANALYSIS
GROUP BY ASIN, PRODUCT_TITLE;


-- 3. Aspect-level sentiment.
CREATE OR REPLACE VIEW VW_ASPECT_SENTIMENT AS
WITH ASPECTS AS (

    SELECT
        REVIEW_ID,
        'Product Quality' AS ASPECT,
        PRODUCT_QUALITY_SENTIMENT AS SENTIMENT
    FROM REVIEW_SENTIMENT_ANALYSIS

    UNION ALL

    SELECT REVIEW_ID, 'Value for Money', VALUE_SENTIMENT
    FROM REVIEW_SENTIMENT_ANALYSIS

    UNION ALL

    SELECT REVIEW_ID, 'Usability', USABILITY_SENTIMENT
    FROM REVIEW_SENTIMENT_ANALYSIS

    UNION ALL

    SELECT REVIEW_ID, 'Durability', DURABILITY_SENTIMENT
    FROM REVIEW_SENTIMENT_ANALYSIS

    UNION ALL

    SELECT REVIEW_ID, 'Packaging', PACKAGING_SENTIMENT
    FROM REVIEW_SENTIMENT_ANALYSIS
)
SELECT
    ASPECT,
    SENTIMENT,
    COUNT(*) AS REVIEW_COUNT
FROM ASPECTS
WHERE SENTIMENT IS NOT NULL
  AND SENTIMENT <> 'unknown'
GROUP BY ASPECT, SENTIMENT;


-- 4. Rating-text mismatch reviews.
CREATE OR REPLACE VIEW VW_RATING_MISMATCH AS
SELECT
    REVIEW_ID,
    ASIN,
    PRODUCT_TITLE,
    MAIN_IMAGE,
    STARS,
    OVERALL_SENTIMENT,
    MISMATCH_TYPE,
    REVIEW_TITLE,
    REVIEW_TEXT,
    VERIFIED_PURCHASE,
    FOUND_HELPFUL,
    REVIEW_DATE
FROM REVIEW_SENTIMENT_ANALYSIS
WHERE RATING_SENTIMENT_MATCH = FALSE;

SHOW VIEWS IN SCHEMA AMAZON_SENTIMENT_DB.ANALYTICS;
